### PR TITLE
Slight design issues fixed

### PR DESCRIPTION
**Pull request by aL3xa**
I added `bootstrap-modal`, removed in-line JS and CSS, and fixed some design issues (like `overflow` properties, etc.) and I renamed some stuff (surprise, surprise)! =P =)

It works. =)

### CODE REVIEW

**Comment by daroczig** [comment]
Wow, thanks a lot Alex, I am really impressed!
You know that I really suck at JS and CSS, your great support was really needed :)

I would like to ask for a small modification in your (otherwise) cool code before merging: now "Run R!" button does not work as `terminal is not defined`. It seems that the `terminal` variable was defined in jQuery's `ready` function which is not reachable by `send2R` which is in the global envir (or how it's called in JS).

IMHO dropping my `send2R` function might be an option and copying the body to `$('#send_r').click(function()`.

**Comment by daroczig** [comment]
Wow, that's what I call a quickfix :)
Thanks a lot!

**Comment by daroczig** [comment]
One thing @aL3xa: the page is a bit messed up while getting a lengthy output after redesigning/moving the footer.

Try running e.g.:

```
plot(mtcars)
runif(10)
```

Not sure if the footer could be tweaked to stay on the bottom of the screen or if it's full then at the end of the page. Lame question I know! :)

**Comment by aL3xa** [comment]
OK, as soon as I finish the hi-pri stuff, I'll add tabs/icons to output. IMO, you should have something like: output, plots, and... what else should be taken into account? Is there any other output type that didn't came to my mind?

**Comment by aL3xa** [comment]
Oh, and I see what you mean now. My mistake. `it { should_have "position: fixed" }` =)
If you're impatient you can change that yourself, but I'll do more UI tweeks there soon, so don't worry 'bout that.

**Pull request merged**
